### ISSUE TITLE
图片爬取缺失

### ISSUE THREAD

**Issue by Neppah** [ph0ebus/XianZhiCrawler#1]
你好，这篇文章爬取的图片数量不足，
https://xz.aliyun.com/t/16480
通过脚本只能爬取到5张图片，增加了sleep 5也存在这个问题，多次尝试稳定复现这个问题。

**Comment by ph0ebus** [comment]
![image](https://github.com/user-attachments/assets/2e7265e3-2ad6-4e43-b05e-abd0f807ce65)
感谢提出问题，估计是tomd这个项目很久没维护了，在html转md的时候由于某些bug缺失了很多信息，后续有空用html2text改一下

**Comment by Neppah** [comment]
PR已解决
